---
version: 2
snapshots:
- name: "customers_scd2"
  columns:
  - name: "customer_id"
    dataType:
      type: "Integer"
  - name: "first_name"
    dataType:
      type: "String"
  - name: "last_name"
    dataType:
      type: "String"
  - name: "updated_at"
    dataType:
      type: "Date"
